SmartContractNethereum/SmartContractNethereum.Web/Controllers/WalletController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SmartContractNethereum.Data.EF;
using SmartContractNethereum.Servicios;
using System.Drawing;

namespace SmartContractNethereum.Web.Controllers
{
    public class WalletController : Controller
    {

        private readonly ITransaccionServicio _transaccionServicio;
        private readonly INethereumServicio _nethereumServicio;

        public WalletController (ITransaccionServicio transaccionServicio, INethereumServicio nethereumServicio) 
        {
            _transaccionServicio = transaccionServicio;
            _nethereumServicio = nethereumServicio; 
         }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            ViewBag.Transacciones = _transaccionServicio.ListarTransacciones();
            return View();
        }

       
        public ActionResult Crear()
        {
            ViewBag.Transacciones = _transaccionServicio.ListarTransacciones();
            return View(new Transaction());
        }

        // POST: WalletController/Create
        [HttpPost]
        public ActionResult Crear(string? sernderAdress, string? receiberAdress, decimal quantityTokens)
        {
            try
            {
                _nethereumServicio.TransactionEther(sernderAdress, receiberAdress, quantityTokens);
                System.Threading.Thread.Sleep(3000);
                return RedirectToAction("Listar");
            }
            catch(Exception e)
            {
                Console.WriteLine(e.ToString());
                return View();
            }
            }


    }
}

SmartContractNethereum/SmartContractNethereum.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartContractNethereum.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartContractNethereum.Web.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Programacion Web 3 - Blockchain
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SmartContractNethereum/SmartContractNethereum.Web/Views/Wallet/Crear.cshtml
@using SmartContractNethereum.Data.EF
@model Transaction
@{
    ViewData["Title"] = "Crear Transaccion";
}

<style>
    .div-redondeado {
        border-radius: 10px;
        border: 2px solid white;
        padding: 20px;
        transition: background-color 0.3s;
    }

        .div-redondeado:hover {
            background-color: #e19152;
        }
</style>
<div class="bg-dark text-light p-4">
    <div class="d-flex flex-row align-items-center align-content-center justify-content-center">
        <a asp-area="" asp-controller="Wallet" asp-action="Index"> <img src="~/img/wall-emask 1.png" class="m-5" /></a> <h3>BidbayMask</h3>
    </div>
    <h1 class="mb-5 text-center">Crear Transacción</h1>
    <div class="mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="div-redondeado">
                    <div>
                        <form action="Crear" method="post">
                            <div class="form-group mb-4">
                                <label class="mb-2" for="senderAddress">Clave Privada:</label>
                                <div class="d-flex">
                                    <input class="form-control" type="password" name="sernderAdress" value="@Model.SenderAddress" />
                                    <small class="form-text text-muted">
                                        <button type="button" class="btn btn-sm btn-secondary info-btn" data-toggle="tooltip" data-placement="top" title="Información general sobre tu clave privada">i</button>
                                    </small>
                                </div>
                            </div>
                            <div class="form-group mb-4">
                                <label class="mb-2" for="receiverAddress">Dirección Destino:</label>
                                <div class="d-flex">
                                    <input class="form-control" type="text" name="receiberAdress" value="@Model.RecieverAddress" />
                                    <small class="form-text text-muted">
                                        <button type="button" class="btn btn-sm btn-secondary info-btn" data-toggle="tooltip" data-placement="top" title="Información general sobre la dirección del destinatario">i</button>
                                    </small>
                                </div>
                            </div>
                            <div class="form-group mb-5">
                                <label class="mb-2" for="quantityTokens">Cantidad de Tokens:</label>
                                <div class="d-flex">
                                    <input class="form-control" type="number" name="quantityTokens" value="@Model.QuantityTokens" min="0" max="100" />
                                    <small class="form-text text-muted">
                                        <button type="button" class="btn btn-sm btn-secondary info-btn " data-toggle="tooltip" data-placement="top" title="Información general sobre la cantidad de tokens">i</button>
                                    </small>
                                </div>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-secondary">Crear Transaccion</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

SmartContractNethereum/SmartContractNethereum.Web/Views/Wallet/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="d-flex flex-column justify-content-center align-items-center text-light">
    <div class="d-flex flex-row align-items-center align-content-center justify-content-center">
        <a asp-area="" asp-controller="Wallet" asp-action="Index"> <img src="~/img/wall-emask 1.png" class="m-5" /></a> <h3>BidbayMask</h3>
    </div>
    <a class="btn btn-primary p-4 rounded-pill m-5 w-50 h-50 font-weight-bold text-capitalize" asp-area="" asp-controller="Wallet" asp-action="Listar">Lista de transacciones</a>
    <a class="btn btn-primary p-4 rounded-pill m-5 w-50 h-50 font-weight-bold text-capitalize" asp-area="" asp-controller="Wallet" asp-action="Crear">Mandar Tokens</a>
</div>

SmartContractNethereum/SmartContractNethereum.Web/Views/Wallet/Listar.cshtml
@using SmartContractNethereum.Data.EF
@{
    ViewData["Title"] = "Listar Transacciones";
}


<div class="bg-dark text-light p-4">
    <div class="d-flex flex-row align-items-center align-content-center justify-content-center">
        <a asp-area="" asp-controller="Wallet" asp-action="Index"> <img src="~/img/wall-emask 1.png" class="m-5" /></a> <h3>BidbayMask</h3>
    </div>
    <h1 class="text-center">Transacciones</h1>
    <table class="table text-light">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Adress receptor</th>
                <th scope="col">Balance de receptor</th>
                <th scope="col">Adress emisor</th>
                <th scope="col">Balance emisor</th>
                <th scope="col">Cantidad de tokens enviados</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Transaction transaccion in ViewBag.Transacciones)
            {
                <tr>
                    <td>@transaccion.Id</td>
                    <td>@transaccion.RecieverAddress</td>
                    <td>@transaccion.ReceiverBalance</td>
                    <td>@transaccion.SenderAddress</td>
                    <td>@transaccion.SenderBalance</td>
                    <td>@transaccion.QuantityTokens</td>
                </tr>
            }
        </tbody>
    </table>
</div>